#!/bin/bash

CLOSURE=~/util/closure/compiler.jar
INFILE=src/jquery.zcarousel.js

MINFILE=${INFILE/.js/.min.js}
CSSFILE=${INFILE/.js/.css}
SPINFILE=`dirname $INFILE`/spin.min.js

# Check it all exists
stat $INFILE >/dev/null || exit
stat $CSSFILE >/dev/null || exit
stat $SPINFILE >/dev/null || exit

echo Writing $MINFILE...
java -jar $CLOSURE $INFILE  >$MINFILE

OUTFILE1=jquery.zcarousel.zip
OUTFILE2=jquery.zcarousel.min.zip
echo Writing $OUTFILE1...
zip $OUTFILE1 $CSSFILE $INFILE $SPINFILE
echo Writing $OUTFILE2...
zip $OUTFILE2 $CSSFILE $MINFILE $SPINFILE


